# Generated by Django 5.1.5 on 2025-01-18 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('genre', models.CharField(choices=[('Homme', 'Homme'), ('Femme', 'Femme'), ('Autre', 'Autre')], max_length=6)),
                ('adresse', models.TextField()),
                ('type_utilisateur', models.CharField(choices=[('Mentor', 'Mentor'), ('Mentoré', 'Mentoré'), ('Administrateur', 'Administrateur')], max_length=14)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('age__gt', 15)), name='age_greater_than_15')],
            },
        ),
    ]
