# Generated by Django 5.1.4 on 2025-04-28 14:20

import app_mentorlink.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_mentorlink', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilisateur',
            name='age',
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='date_naissance',
            field=models.DateField(blank=True, null=True, validators=[app_mentorlink.models.validate_birthdate]),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='civilite',
            field=models.CharField(blank=True, choices=[('Homme', 'Homme'), ('Femme', 'Femme'), ('Autre', 'Autre')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='utilisateur_groups', related_query_name='utilisateur', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='utilisateur_permissions', related_query_name='utilisateur', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
