# Generated by Django 5.1.5 on 2025-02-11 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_mentorlink', '0005_remove_annonces_age_remove_annonces_nom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='annonces',
            name='description',
            field=models.TextField(blank=True, max_length=100000, null=True),
        ),
    ]
