version: '3.8'

services:
  web:
    build: .
    restart: always
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    depends_on:
      - db
    environment:
      - DEBUG=0
      - SECRET_KEY=changeme
      - DJANGO_ALLOWED_HOSTS=*
      - DB_HOST=db
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    expose:
      - "8000"
    command: >
      sh -c "
        cd /app/mentor_link &&
        python manage.py collectstatic --noinput &&
        python manage.py migrate &&
        daphne -b 0.0.0.0 -p 8000 main.asgi:application
      "

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db_data:/var/lib/postgresql/data

  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web

volumes:
  static_volume:
  media_volume:
  db_data:
