# Generated by Django 5.1.5 on 2025-01-18 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_mentorlink', '0003_alter_utilisateur_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Annonces',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('prix', models.IntegerField()),
                ('url_photo', models.CharField(max_length=1000)),
                ('metier', models.CharField(max_length=1000)),
                ('adresse', models.TextField()),
            ],
        ),
    ]
