# Generated by Django 5.1.5 on 2025-01-18 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_de_donnee', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='utilisateur',
            old_name='type_utilisateur',
            new_name='role',
        ),
    ]
