# Generated by Django 5.1.5 on 2025-02-03 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_de_donnee', '0004_annonces'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annonces',
            name='age',
        ),
        migrations.RemoveField(
            model_name='annonces',
            name='nom',
        ),
        migrations.RemoveField(
            model_name='annonces',
            name='prenom',
        ),
        migrations.AddField(
            model_name='annonces',
            name='id_personnes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base_de_donnee.utilisateur'),
        ),
    ]
