# Generated by Django 5.1.5 on 2025-01-18 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_de_donnee', '0002_rename_type_utilisateur_utilisateur_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
